#!/bin/bash

set -e

log() {
	local msg="$1"

	echo "[BOOTSTRAP]==> $msg"
}

root=$(dirname $(dirname $0))
deproot=${1:-".."}
pom="$root/pom.xml"
repos=$(grep '<!-- GIT ' $pom | sed -re 's,.*GIT ([^ ]+).*,\1,g')

for repo in $repos; do
	dir=$(basename $repo .git)

	if [ -d "$root/$deproot/$dir" ]; then
		log "Updating repository: $repo"
		(cd "$root/$deproot/$dir" && git pull origin master)
	else
		log "Cloning repository: $repo"
		git clone $repo "$root/$deproot/$dir"
	fi
done

log "Creating build-pom.xml"
sed -re "s,<module>\.\./,<module>$deproot/,g" pom.xml > build-pom.xml

exit 0
