#!/bin/bash

set -e

log() {
	local msg="$1"

	echo "[BOOTSTRAP]==> $msg"
}

root=$(dirname $(dirname $0))
deproot=${1:-".."}
pom="$root/pom.xml"
repos=$(grep '<!-- GIT ' $pom | sed -re 's,.*GIT ([^ ]+).*,\1,g')

for repo_and_tag in $repos; do
	repo=$(echo $repo_and_tag | cut -d '=' -f 1)
	rev=$(echo $repo_and_tag | cut -d '=' -f 2)
	dir=$(basename $repo .git)

	if [ -z "$rev" -o "$rev" = "$repo" ]; then
		log "WARNING: No rev given in '$repo_and_tag', using default: master"
		rev="master"
	fi

	if [ -d "$root/$deproot/$dir" ]; then
		log "Updating repository: $repo"
		(cd "$root/$deproot/$dir" && git checkout master && git fetch --all --tags && git pull origin master)
	else
		log "Cloning repository: $repo"
		git clone $repo "$root/$deproot/$dir"
	fi

	log "Checkout revision: $rev in $repo"
	(cd "$root/$deproot/$dir" && git checkout -f -B build-$rev $rev)

done

log "Creating build-pom.xml"
sed -re "s,<module>\.\./,<module>$deproot/,g" pom.xml > build-pom.xml

exit 0
