#!/bin/sh

prefix=$(dirname $0)

. ${prefix}/includes

check_for_server_dir

pluginname=$1
if [ -z $pluginname ]; then
  err "Syntax: $0 <plugin name>"
fi

if [ -d $pluginname ]; then
  err "There is already a plugin with that name. Cowardly refusing to overwrite it."
fi

mvn archetype:generate -DarchetypeGroupId=org.graylog -DarchetypeArtifactId=graylog-plugin-archetype -DartifactId=$pluginname

echo ${pluginname}/ >> ${prefix}/.gitignore
