#!/bin/sh

prefix=$(dirname $0)

. ${prefix}/includes

check_for_server_dir

pluginname=graylog-plugin-$1
if [ -z $1 ]; then
  err "Syntax: $0 <plugin name>"
fi

if [ -d $pluginname ]; then
  err "There is already a plugin with that name. Cowardly refusing to overwrite it."
fi

mvn archetype:generate -DarchetypeGroupId=org.graylog -DarchetypeArtifactId=graylog-plugin-archetype -DartifactId=$pluginname

buildConf=${modulesPrefix}/${pluginname}/build.config.js
cp ${buildConf}.sample ${buildConf}

grep -q ${pluginname} ${gitignore} || printf "\n%s\n" "${pluginname}" >> ${gitignore}

pushd 2> /dev/null
cd $pluginname
mvn generate-resources
popd 2> /dev/null
