#!/bin/sh

err() {
  echo $1
  exit -1
}

prefix=$(dirname $0)
serverDir=../graylog2-server

if [ ! -d $serverDir ]; then
  err "There is no directory for the server checkout ($serverDir).Please run $prefix/bootstrap first."
fi

pluginname=$1
if [ -z $pluginname ]; then
  err "Syntax: $0 <plugin name>"
fi

if [ -d $pluginname ]; then
  err "There is already a plugin with that name. Cowardly refusing to overwrite it."
fi

buildConfigFilename=${pluginname}/build.config.js

mvn archetype:generate -DarchetypeGroupId=org.graylog -DarchetypeArtifactId=graylog-plugin-archetype -DartifactId=$pluginname

sed 's,\(../graylog2-server/graylog2-web-interface\),../\1/,' < ${buildConfigFilename}.sample > ${buildConfigFilename}
