#!/bin/bash

set -e

root=$(dirname $(dirname $0))

# Rename the artifacts from .tar.gz to .tgz
find "$root/target" -type f -name 'graylog-*.tar.gz' | while read file; do
	mv "$file" "$(dirname $file)/$(basename $file .tar.gz).tgz"
done

# Generate artifact checksums
find "$root/target" -type f -name 'graylog-*.tgz' | while read file; do
	dir=$(dirname $file)
	artifact=$(basename $file)
	echo "########## Building Checksums ##########"
	echo -n "MD5:    "
	(cd $dir && md5sum "${artifact}" | tee "${artifact}.md5.txt")
	echo -n "SHA1:   "
	(cd $dir && sha1sum "${artifact}" | tee "${artifact}.sha1.txt")
	echo -n "SHA256: "
	(cd $dir && sha256sum "${artifact}" | tee "${artifact}.sha256.txt")
done

exit 0
